project_id = "vvunxewylcifwphxgqab"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.challenge-validation]
verify_jwt = true

[functions.generate-challenge]
verify_jwt = true

[functions.match-challenge]
verify_jwt = true

[functions.verify-admin-access]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-general-contact]
verify_jwt = false

[functions.translate-challenge]
verify_jwt = true